title:               Deep Multi-Task Learning for SSVEP Detection and Visual Response Mapping
description:         "Using multi-task learning to efficiently captures signals simultaneously from the fovea and the neighboring targets in the peripheral vision, generating a visual response map. A calibration-free user-independent solution, desirable for clinical diagnostics. A stepping stone for an objective assessment of glaucoma patients' visual field."
url:                 https://jinglescode.github.io/ssvep-multi-task-learning/
baseurl:             '/ssvep-multi-task-learning'
permalink:           pretty

author:
  name:              Khok Hong Jing
  url:               https://jinglescode.github.io/
  email:             jinglescode@gmail.com

defaults:
  - scope:
      path: "*"
    values:
      layout: default

paper_linK: https://github.com/jinglescode/ssvep-multi-task-learning/blob/master/Deep-Multi-Task-Learning-for-SSVEP-Detection-and-Visual-Response-Mapping.pdf
github_link: https://github.com/jinglescode/ssvep-multi-task-learning
medium_linK: https://towardsdatascience.com/improve-glaucoma-assessment-with-brain-computer-interface-and-machine-learning-6c3b774494f8

google_analytics_id: UA-49548145-2

sass:
    sass_dir: ./public/sass